### ISSUE TITLE
Stevenson Screen

### ISSUE THREAD

**Issue by JTWWilson** [fabcooldog/BGS-Weather-Station#1]
In the proposed box design, we may not receive the most accurate temperature reading due to not using a [Stevenson screen](https://en.wikipedia.org/wiki/Stevenson_screen) to protect the sensors from wind and sun.

**Comment by AWilliams1011** [comment]
We ARE using a Stevenson's screen, I just haven't designed it yet

**Comment by AWilliams1011** [comment]
I will design it as when SolidWorks stops crashing every 10 mins

**Comment by JTWWilson** [comment]
Do you have the portable version for home use?

**Comment by AWilliams1011** [comment]
What do you mean?

**Comment by JTWWilson** [comment]
Was it not the school computer that was the problem?

**Comment by AWilliams1011** [comment]
I do not know

It may have something to do with the fact I am using SolidWorks 2017 at home and SolidWorks 2016 at school

**Comment by AWilliams1011** [comment]
At least I think I am (I can't check now)

**Comment by AWilliams1011** [comment]
The version of files that I have just uploaded has half a Stevenson's screen
